# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ghambrec <ghambrec@student.42heilbronn.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/12/07 10:41:45 by ghambrec          #+#    #+#              #
#    Updated: 2026/02/20 13:43:04 by ghambrec         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# compiling stuff
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++17
FLAG_OPTIMIZING = -O2
FLAG_DEBUG = -g -O0

# header files
INCLUDE = ./inc
CXXFLAGS += -I$(INCLUDE)

# program name
NAME = BitcoinExchange

# source files
VPATH =	src
SRCS =	main.cpp \
		BitcoinExchange.cpp

# obejct files
OBJ_DIR = obj
OBJS = $(addprefix $(OBJ_DIR)/, $(SRCS:.cpp=.o))

all: CXXFLAGS += $(FLAG_OPTIMIZING)
all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(OBJS) -o $(NAME)

# .cpp zu .o
$(OBJ_DIR)/%.o: %.cpp | $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(OBJ_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

debug: CXXFLAGS += $(FLAG_DEBUG)
debug: $(NAME)

run: $(NAME)
	./$(NAME)

valgrind: fclean debug
	valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all ./$(NAME)

.PHONY: all clean fclean re run debug valgrind
